# ====================================
# DOCKER COMPOSE - Ain'tonio Discord Bot
# Actualizado con volúmenes de Docker
# ====================================

version: '3.8'

services:
  # ====================================
  # SERVICIO PRINCIPAL DEL BOT
  # ====================================
  discord-bot:
    image: raztor/aintonio-bot:latest
    container_name: aintonio-discord-bot
    restart: unless-stopped

    # Variables de entorno desde archivo .env
    env_file:
      - .env

    # Variables adicionales del contenedor
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src

    # Volúmenes de Docker (no carpetas mapeadas)
    volumes:
      - bot_logs:/app/logs
      - bot_data:/app/data
      - bot_resources:/app/src/resources

    # Configuración de red
    networks:
      - bot-network

    # Configuración de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.insert(0, '/app/src'); from config.settings import get_settings; get_settings().validate()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ====================================
# REDES
# ====================================
networks:
  bot-network:
    driver: bridge
    name: aintonio-network

# ====================================
# VOLÚMENES DE DOCKER
# ====================================
volumes:
  bot_logs:
    driver: local
    name: aintonio_logs
  bot_data:
    driver: local
    name: aintonio_data
  bot_resources:
    driver: local
    name: aintonio_resources